export default [
  {
  "nick": "FlyRouter",
  "descr": "Project Coordination, Documentation",
  "img": "https://avatars.githubusercontent.com/u/88846",
  "githubNick": "ZigFisher",
  "telegramNick": "FlyRouter",
  },
  {
  "nick": "widgetii",
  "descr": "Majestic Streamer, IPCtool",
  "img": "https://avatars.githubusercontent.com/u/6576495",
  "githubNick": "widgetii",
  "telegramNick": "widgetii",
  },
  {
  "nick": "dimerrr",
  "descr": "U-Boot, Kernels, Coupler, IPCtool",
  "img": "https://avatars.githubusercontent.com/u/106577375",
  "githubNick": "dimerrr",
  "telegramNick": "dimerrr",
  },
  {
  "nick": "John",
  "descr": "Linux",
  "img": "https://avatars.githubusercontent.com/u/21039610",
  "githubNick": "p0i5k",
  "telegramNick": "p0i5k",
  },
  {
  "nick": "Hirrolot",
  "descr": "SmolRTSP",
  "img": "https://avatars.githubusercontent.com/u/40539574",
  "githubNick": "Hirrolot",
  "telegramNick": "hirrolot",
  },
  {
  "nick": "cronyx",
  "descr": "Linux",
  "img": "https://avatars.githubusercontent.com/u/2557102",
  "githubNick": "cronyx",
  "telegramNick": "cronyx",
  },
  {
  "nick": "chertov",
  "descr": "Mini Streamer",
  "img": "https://avatars.githubusercontent.com/u/436625",
  "githubNick": "chertov",
  "telegramNick": "mAX3773",
  },
  {
  "nick": "SSharshunov",
  "descr": "The ex researcher",
  "img": "https://avatars.githubusercontent.com/u/2909755",
  "githubNick": "SSharshunov",
  "telegramNick": "USSSSSH",
  },
  {
  "nick": "themactep",
  "descr": "Project Coordination, Documentation",
  "img": "https://avatars.githubusercontent.com/u/37488",
  "githubNick": "themactep",
  "telegramNick": "themactep",
  },
]
